# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: '#about'
    weight: 10
  - name: Contents
    url: '#contents'
    weight: 5
  - name: Papers
    url: '#papers'
    weight: 20
  - name: Experience
    url: '#job-experience'
    weight: 30
  - name: Education
    url: '#education'
    weight: 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
